### ISSUE TITLE
Move Sequences don't seem to work fully

### ISSUE THREAD

**Issue by ogruendel** [TwitchSolvesCube/TwitchSolvesCubeV2#10]
Will do further digging what causes this, but for now here is the issue and a video showing it: https://clips.twitch.tv/OpenCarelessPieThisIsSparta-ZMVQ2tNH5ADqwOcF

**Comment by ogruendel** [comment]
Sequences on their own work fine, however once a second sequence gets called, the first one seems to just cut out and start the next one

**Comment by TwitchSolvesCube** [comment]
Thank you for finding this bug! Just fixed the issue in this [commit](https://github.com/TwitchSolvesCube/TwitchSolvesCubeV2/commit/628b1449d5bfb09087689abb200d4cfec3da8a26). Moved where disabling the cube is done as it only needs to be disabled when performing algorithms, which also disables the cube on scrambles.
